have to use these types in project for code reuse
mindbox-moscow/redux-helpers pull request #10
Opened 2017-10-16 15:25 UTC by timramone

2017-10-16 15:26 UTC, timramone commented
review me someone plz

2017-10-17 10:37 UTC, d-i-bondarenko requested changes

2017-10-17 10:37 UTC, d-i-bondarenko commented on ts/helpers.ts
> +export interface GuardedReducerBase<TPayload, TState>
У нас экспорты внизу файла.

2017-10-17 10:41 UTC, d-i-bondarenko approved these changes

2017-10-17 10:47 UTC, merged